### PR TITLE
Fix #29: Actually create a source map if it is requested

### LINKED ISSUE #29: -s does not seem to produce a source map
I'm wondering if I am calling it wrong, but when I use `-s` no source map is produced e.g. `scalajsld -s -r -d -f -K ESModule -o blah.js <classpath stuff>`. I get a .js file with everything in it but no source map is next to it, e.g., `blah.js.map` and there is no source map reference at the bottom of blah.js.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

File: scripts/test-cli.sh [hunk 1]
```diff
@@ -47,11 +47,15 @@ if [ ! -s out ]; then
...
 
-scalajsld -o test.js -mm Foo.main bin
+scalajsld -s -o test.js -mm Foo.main bin
 if [ ! -s test.js ]; then
     echo "scalajsld: empty output";
 fi
 
+if [ ! -s test.js.map ]; then
+    echo "scalajsld: empty source map";
+fi
```
Comment (sjrd) [inline scripts/test-cli.sh]: Again, this should probably fail the script.

File: src/main/scala/org/scalajs/cli/Scalajsld.scala [hunk 2]
```diff
@@ -169,8 +170,19 @@ object Scalajsld {
...
+        val js = options.output.toPath()
+        val sm = js.resolveSibling(js.getFileName().toString() + ".map")
+
+        def relURI(f: Path) =
+          new URI(null, null, f.getFileName().toString, null)
+
+        LinkerOutput(PathOutputFile(js))
+          .withSourceMap(PathOutputFile(sm))
+          .withSourceMapURI(relURI(sm))
+          .withJSFileURI(relURI(js))
```
Comment (sjrd) [inline src/main/scala/org/scalajs/cli/Scalajsld.scala:184]: I believe we should only do this if `options.sourceMap` is true.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: src/main/scala/org/scalajs/cli/Scalajsld.scala (hunk 2 above)
Comment (gzm0) [reply src/main/scala/org/scalajs/cli/Scalajsld.scala:184]: We have explicitly allowed this (see the doc of LinkerOutput). In fact the sbt plugin itself uses this.

**Review by sjrd — APPROVED** [review]
